export const MenuData = {
  MAINDISHES: [
    {
      id: 1,
      name: "PLOV",
      description: "Central Asian rice w beef and carrots",
      image: "/menuitems/Uzgen-plov.webp",
      categories: [""],
      price: 15,
    },
    {
      id: 2,
      name: "PLOV with KAZY",
      description: "Rice with beef, carrots, and traditional sausage",
      image: "",
      categories: [""],
      price: 17,
    },
    {
      id: 3,
      name: "UZGEN PLOV",
      description: "Central Asian brown rice w beef and carrots",
      image: "/assets/Uzgen-plov.jpg",
      categories: [""],
      price: 17,
    },
    {
      id: 4,
      name: "LAMB KUURDAK",
      description: "Stewed lamb with potatoes and onions",
      image: "/menuitems/Lamb-kuurdak.webp",
      categories: [""],
      price: 22,
    },
    {
      id: 5,
      name: "CHICKEN KUURDAK",
      description: "Stewed chicken with potatoes and onions",
      image: "/menuitems/Chicken-kuurdak.webp",
      categories: [""],
      price: 15,
    },
    {
      id: 6,
      name: "BESHBARMAK",
      description: "Finely chopped boiled beef with egg noodles",
      image: "/menuitems/Beshbarmak.webp",
      categories: [""],
      price: 18,
    },
    {
      id: 7,
      name: "JIZ-BIZ",
      description: "Fried lamb pieces with french fries",
      image: "/menuitems/Jiz-Biz.webp",
      categories: [""],
      price: 22,
    },
    {
      id: 8,
      name: "MANTY",
      description: "Central Asian style dumplings, stuffed w beef and onions",
      image: "/menuitems/Pumpkin-manty.webp",
      categories: [""],
      price: 15,
    },
    {
      id: 9,
      name: "PUMPKIN MANTY",
      description: "Central Asian style dumplings, stuffed with pumpkin and onions",
      image: "/menuitems/Pumpkin-manty.webp",
      categories: [""],
      price: 12,
    },
    {
      id: 10,
      name: "OROMO",
      description:
        "Traditional-steamed pie stuffed with minced meat, potatoes&onions",
      image: "/menuitems/Oromo.webp",
      categories: [""],
      price: 13,
    },
    {
      id: 11,
      name: "GAN-FAN",
      description: "Sauteed beef, peppers, onions served over rice",
      image: "/menuitems/Gan-fan.webp",
      categories: [""],
      price: 14,
    },
    {
      id: 12,
      name: "GYURO LAGMAN",
      description: "Stir fried beef & vegetables served w hand-pulled noodles",
      image: "/menuitems/Gyuro-lagman.webp",
      categories: [""],
      price: 20,
    },
    {
      id: 13,
      name: "BOSO LAGMAN",
      description: "Hand-pulled noodles stir fried with beef & vegetables",
      image: "/menuitems/Boso-lagman.webp",
      categories: [""],
      price: 18,
    },
    {
      id: 14,
      name: "ACHUU ET",
      description: "Traditional Uyghur meal, spicy beef and vegetables",
      image: "/menuitems/Achuu-et.webp",
      categories: [""],
      price: 19,
    },
    {
      id: 15,
      name: "TANDOOR SAMSA",
      description: "Stuffed pastry made w beef, onion and cooked in tandoor",
      image: "/menuitems/Tandoor-samsa.webp",
      categories: [""],
      price: 7,
    },
    {
      id: 16,
      name: "BEEF SHASHLYK",
      description: "1 skewer of grilled beef cubes served with rice and vegies",
      image: "/menuitems/Beef-shashlyk.webp",
      categories: [""],
      price: 12,
    },
    {
      id: 17,
      name: "LULYA KEBAB",
      description: "1 skewer of grilled minced beef served w rice and vegies",
      image: "/menuitems/Lulya-kebab.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 18,
      name: "LAMB CHOPS",
      description: "1 skewer of grilled lamb chops served w rice and vegies",
      image: "/menuitems/Lamb-chops.webp",
      categories: [""],
      price: 17,
    },
    {
      id: 19,
      name: "CHICKEN SHASHLYK",
      description:
        "1 skewer of grilled chicken wings or breast with rice and vegies",
      image: "/menuitems/Chicken-shashlyk.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 20,
      name: "MIXED SHASHLYK",
      description:
        "4 skewers: beef&chicken shashlyks, lamb chops and lulya kebab served with rice and french fries",
      image: "/menuitems/Mixed-shashlyk.webp",
      categories: [""],
      price: 49,
    },
  ],
  SOUPS: [
    {
      id: 1,
      name: "LAMB SOUP",
      description: "Central Asian lamb soup with vegetables",
      image: "",
      categories: [""],
      price: 12,
    },
    {
      id: 2,
      name: "BEEF SOUP",
      description: "Central Asian beef soup with vegetables",
      image: "/menuitems/Beef-soup.webp",
      categories: [""],
      price: 11,
    },
    {
      id: 3,
      name: "CHUCHVARA",
      description:
        "Ground beef stuffed dumplings served in a soup with vegetables",
      image: "/menuitems/Chuchvara.webp",
      categories: [""],
      price: 12,
    },
    {
      id: 4,
      name: "PELMENI",
      description: "Ground beef stuffed dumplings in a flavorful broth",
      image: "",
      categories: [""],
      price: 10,
    },
    {
      id: 5,
      name: "MASTAVA",
      description: "Thick, hearty soup of rice, meat, vegetables",
      image: "/menuitems/Mastava.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 6,
      name: "LAGMAN",
      description: "Hand-pulled noodle soup with beef and vegetables",
      image: "/menuitems/Lagman.webp",
      categories: [""],
      price: 16,
    },
    {
      id: 7,
      name: "LENTIL SOUP",
      description: "Classic lentil soup served with lemon",
      image: "/menuitems/Lentil-soup.webp",
      categories: [""],
      price: 5,
    },
    {
      id: 8,
      name: "CHICKEN SOUP",
      description: "Simmered to perfection with chicken pieces & vegetables",
      image: "/menuitems/Chicken-soup.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 9,
      name: "FISH SOUP ",
      description: "Signature fish soup made with shrimps",
      image: "",
      categories: [""],
      price: 15,
    },
    {
      id: 10,
      name: "STUFFED PEPPERS",
      description: "Minced beef and rice stuffed bell peppers soup",
      image: "",
      categories: [""],
      price: 10,
    },
  ],
  APPETIZERS: [
    {
      id: 1,
      name: "BOORSOK",
      description: "Fried dough in a shape of puffy pillows",
      image: "/menuitems/Boorsok.webp",
      categories: ["SPECIAL", "H", "V"],
      price: 5,
    },
    {
      id: 2,
      name: "CHICKEN SAMSA",
      description: "Central Asian chicken pastry",
      image: "",
      categories: ["SPECIAL", "H"],
      price: 4.5,
    },
    {
      id: 3,
      name: "BEEF SAMSA",
      description: "Central Asian beef pastry",
      image: "/menuitems/Beef-samsa.webp",
      categories: ["SPECIAL"],
      price: 5.5,
    },
    {
      id: 4,
      name: "RICE",
      description: "A plate of steamed rice",
      image: "",
      categories: ["NEW", "H", "V"],
      price: 3,
    },
    {
      id: 5,
      name: "LEPESHKA",
      description: "Central Asian bread",
      image: "",
      categories: ["H", "V"],
      price: 3.99,
    },
  ],
  SALADS: [
    {
      id: 1,
      name: "CARROT SALAD",
      description: "Crunchy grated carrots dressed with olive oil",
      image: "",
      categories: [""],
      price: 4,
    },
    {
      id: 2,
      name: "SHAKARAP",
      description: "Sliced tomatoes with onions seasoned w salt",
      image: "/menuitems/Shakarap.webp",
      categories: [""],
      price: 3,
    },
    {
      id: 3,
      name: "COBAN SALAD",
      description:
        "Made of tomatoes, bell peppers, red onion, cucumbers & olive oil",
      image: "",
      categories: [""],
      price: 6,
    },
    {
      id: 4,
      name: "AVOCADO SALAD",
      description: "House-made avocado with vegetables salad",
      image: "",
      categories: [""],
      price: 6,
    },
    {
      id: 5,
      name: "OLIVYE",
      description:
        "Hearty blend: potatoes, sausages, peas, carrots, pickles, eggs, mayo, and more!",
      image: "/menuitems/Olivye.webp",
      categories: [""],
      price: 6,
    },
    {
      id: 6,
      name: "GREEK SALAD",
      description: "Crisp Romaine, Creamy Dressing, Parmesan, Garlic Croutons",
      image: "",
      categories: [""],
      price: 10,
    },
    {
      id: 7,
      name: "VECHA SALAD",
      description: "Spicy salad with beef and vegetables",
      image: "",
      categories: [""],
      price: 10,
    },
  ],
  "KIDS MENU": [
    {
      id: 1,
      name: "HALAL BURGER",
      description: "House-made cheeseburger",
      image: "",
      categories: [""],
      price: 9,
    },
    {
      id: 2,
      name: "FRENCH FRIES",
      description: "House-made fries served with ketchup",
      image: "",
      categories: [""],
      price: 3.99,
    },
    {
      id: 3,
      name: "CHICKEN NUGGETS",
      description: "Deep-fried boneless chicken pieces",
      image: "",
      categories: [""],
      price: 7.5,
    },
  ],
  "FASTGRILLEDBROILED": [
    {
      id: 1,
      name: "ARZAN SHAWARMA",
      description: "Beef & lamb wrap with vegies and house-made sauce",
      image: "",
      categories: [""],
      price: 12,
    },
    {
      id: 2,
      name: "CHICKEN SHAWARMA",
      description: "Chicken wrap with vegies and house-made sauce",
      image: "/menuitems/Chicken-shawarma.webp",
      categories: [""],
      price: 11,
    },
    {
      id: 3,
      name: "ASSORTI SHAWARMA",
      description: "Beef, lamb & chicken wrap with vegies and house-made sauce",
      image: "",
      categories: [""],
      price: 12,
    },
    {
      id: 4,
      name: "VEGGIE SHAWARMA",
      description: "Veggie wrap with french fries and vegetables",
      image: "/menuitems/Veggie-Shawarma.webp",
      categories: [""],
      price: 11,
    },
    {
      id: 5,
      name: "SHAWARMA PLATE",
      description: "Beef & lamb mixed shawarma served with rice",
      image: "/menuitems/Shawarma-plate.webp",
      categories: [""],
      price: 14,
    },
    {
      id: 6,
      name: "CHEESEBURGER",
      description: "House-made zabiha halal cheeseburger",
      image: "/menuitems/Cheeseburger.webp",
      categories: [""],
      price: 9,
    },
    {
      id: 7,
      name: "DOUBLE CHEESEBURGER",
      description: "House-made zabiha halal double cheeseburger",
      image: "",
      categories: [""],
      price: 12,
    },
    {
      id: 8,
      name: "CHICKEN BURGER",
      description: "House-made zabiha halal chicken burger",
      image: "",
      categories: [""],
      price: 8,
    },
    {
      id: 9,
      name: "NEW YORK STEAK",
      description:
        "Sizzling, seasoned, a carnivore's delight, with grilled vegetables",
      image: "",
      categories: [""],
      price: 23,
    },
    {
      id: 10,
      name: "RIBEYE STEAK",
      description:
        "Juicy ribeye, grilled to perfection, served with savory sides",
      image: "",
      categories: [""],
      price: 25,
    },
    {
      id: 11,
      name: "T-BONE STEAK",
      description: "Juicy, grilled perfection, served with grilled vegetables",
      image: "",
      categories: [""],
      price: 25,
    },
    {
      id: 12,
      name: "BAKED TROUT",
      description:
        "Seasoned, tender, flaky, and served with grilled vegetables",
      image: "",
      categories: [""],
      price: 20,
    },
    {
      id: 13,
      name: "VEAL ORLOFF",
      description:
        "Classic French dish w thinly sliced roast veal, mushroom, and creamy sauce",
      image: "",
      categories: [""],
      price: 18,
    },
    {
      id: 14,
      name: "GRILLED CHICKEN",
      description: "Grilled chicken served over rice with sauce",
      image: "/menuitems/Grilled-chicken.webp",
      categories: [""],
      price: 12,
    },
  ],
  BEVERAGES: [
    {
      id: 1,
      name: "JARMA (1 GAL)",
      description: "",
      image: "",
      categories: [""],
      price: 25,
    },
    {
      id: 1,
      name: "JARMA (1 Lt)",
      description: "",
      image: "",
      categories: [""],
      price: 7.5,
    },
    {
      id: 1,
      name: "POT OF TEA",
      description: "",
      image: "",
      categories: [""],
      price: 2,
    },
    {
      id: 1,
      name: "COMPOTE (1 Lt)",
      description: "",
      image: "",
      categories: [""],
      price: 6.5,
    },
    {
      id: 1,
      name: "NATAKHTARI (1 Lt)",
      description: "",
      image: "",
      categories: [""],
      price: 5,
    },
    {
      id: 1,
      name: "NATAKHTARI (1 glass)",
      description: "",
      image: "",
      categories: [""],
      price: 3,
    },
    {
      id: 1,
      name: "SODA",
      description: "Coke, Pepsi, Fanta, Sprite",
      image: "",
      categories: [""],
      price: 1.5,
    },
    {
      id: 1,
      name: "SODA (glass bottle)",
      description: "",
      image: "",
      categories: [""],
      price: 3,
    },
  ],
  DESSERTS: [
    {
      id: 1,
      name: "HONEY CAKE",
      description:
        "Thin layer cake made with raw honey and a sour cream frosting",
      image: "",
      categories: [""],
      price: 7,
    },
    {
      id: 1,
      name: "MILK CAKE",
      description: "Russian pancake",
      image: "",
      categories: [""],
      price: 7,
    },
    {
      id: 1,
      name: "SOCHINSKIY",
      description: "Sochinskiy",
      image: "",
      categories: [""],
      price: 4,
    },
  ],
  BREAKFAST: [
    {
      id: 1,
      name: "BREAKFAST PLATE",
      description:
        "Central Asian style breakfast with traditional omlette, blinchik (Russian pancake), a cup of kaimak (sour cream), a cup of honey and a pot of tea.",
      image: "",
      categories: [""],
      price: 9.95,
    },
    {
      id: 2,
      name: "BLINI w TVOROG",
      description: "Russian pancake with cottage cheese",
      image: "",
      categories: [""],
      price: 4,
    },
    {
      id: 3,
      name: "BLINI PLAIN",
      description: "Russian pancake",
      image: "",
      categories: [""],
      price: 2,
    },
    {
      id: 4,
      name: "HONEY",
      description: "1 portion of Central Asian honey",
      image: "",
      categories: [""],
      price: 1,
    },
    {
      id: 5,
      name: "JAM",
      description: "1 portion of strawberry or cherries jam",
      image: "",
      categories: [""],
      price: 1,
    },
    {
      id: 6,
      name: "KAIMAK",
      description: "Central Asian sour cream",
      image: "",
      categories: [""],
      price: 3,
    },
    {
      id: 7,
      name: "LEMON",
      description: "1 portion of a lemon",
      image: "",
      categories: [""],
      price: 1.5,
    },
  ],
  "SPECIALORDER": [
    {
      id: 1,
      name: "Tashkent plov",
      description: "",
      image: "",
      categories: [""],
      price: 140,
    },
    {
      id: 2,
      name: "Uzgen rice plov",
      description: "",
      image: "",
      categories: [""],
      price: 150,
    },
    {
      id: 3,
      name: "Lazer rice plov",
      description: "",
      image: "",
      categories: [""],
      price: 120,
    },
    {
      id: 4,
      name: "Beshbarmak",
      description: "",
      image: "/menuitems/Beshbarmak.webp",
      categories: [""],
      price: 70,
    },
    {
      id: 5,
      name: "Boorsok",
      description: "",
      image: "/menuitems/Boorsok.webp",
      categories: [""],
      price: 20,
    },
    {
      id: 6,
      name: "Kuurdak (2 kg min)",
      description: "",
      image: "",
      categories: [""],
      price: 65,
    },
  ],
};
