export const MenuData = {
  MAINDISHES: [
    {
      id: 1,
      name: "PLOV",
      description: "Central Asian rice w beef and carrots",
      image: "/menuitems/Plov.webp",
      categories: [""],
      price: 15.99,
    },
    /*{
      id: 2,
      name: "PLOV with KAZY",
      description: "Rice with beef, carrots, and traditional sausage",
      image: "",
      categories: [""],
      price: 17,
    },
    {
      id: 3,
      name: "UZGEN PLOV",
      description: "Central Asian brown rice w beef and carrots",
      image: "/assets/Uzgen-plov.jpg",
      categories: [""],
      price: 17,
    },*/
    {
      id: 4,
      name: "LAMB KUURDAK",
      description: "Stewed lamb with potatoes and onions",
      image: "/menuitems/Lamb-kuurdak.webp",
      categories: [""],
      price: 25.99,
    },
    /*{
      id: 6,
      name: "BESHBARMAK",
      description: "Finely chopped boiled beef with egg noodles",
      image: "/menuitems/Beshbarmak.webp",
      categories: [""],
      price: 18,
    },*/
    /*{
      id: 7,
      name: "JIZ-BIZ",
      description: "Fried lamb pieces with french fries",
      image: "/menuitems/Jiz-Biz.webp",
      categories: [""],
      price: 22,
    },*/
    {
      id: 8,
      name: "MANTY",
      description: "Central Asian style dumplings, stuffed w beef and onions",
      image: "/menuitems/Manty.webp",
      categories: [""],
      price: 16.99,
    },
    /*{
      id: 9,
      name: "PUMPKIN MANTY",
      description: "Central Asian style dumplings, stuffed with pumpkin and onions",
      image: "/menuitems/Pumpkin-manty.webp",
      categories: [""],
      price: 12,
    },*/
    {
      id: 10,
      name: "OROMO",
      description:
        "Traditional-steamed pie stuffed with minced meat, potatoes&onions",
      image: "/menuitems/Oromo.webp",
      categories: [""],
      price: 15.99,
    },
    {
      id: 11,
      name: "GAN-FAN",
      description: "Sauteed beef, peppers, onions served over rice",
      image: "/menuitems/Gan-fan.webp",
      categories: [""],
      price: 16.99,
    },
    {
      id: 12,
      name: "LAGMAN",
      description: "Hand-pulled noodle soup with beef and vegetables",
      image: "/menuitems/Lagman.webp",
      categories: [""],
      price: 16.99,
    },
    {
      id: 13,
      name: "BOSO LAGMAN",
      description: "Hand-pulled noodles stir fried with beef & vegetables",
      image: "/menuitems/Boso-lagman.webp",
      categories: [""],
      price: 19.99,
    },
    {
      id: 14,
      name: "ACHUU ET",
      description: "Traditional Uyghur meal, spicy beef and vegetables",
      image: "/menuitems/Achuu-et.webp",
      categories: [""],
      price: 23.99,
    },
    {
      id: 5,
      name: "BEEF CUTLETS",
      description: "Two beef cutlets, pan-fried and breaded, served with mashed potatoes",
      image: "/menuitems/Beef-cutlets.webp",
      categories: [""],
      price: 15.99,
    },
    {
      id: 15,
      name: "TANDOOR SAMSA",
      description: "Stuffed pastry made w beef, onion and cooked in tandoor",
      image: "/menuitems/Tandoor-samsa.webp",
      categories: [""],
      price: 7.49,
    },
  ],
  SOUPS: [
    {
      id: 1,
      name: "LAMB SOUP",
      description: "Central Asian lamb soup with vegetables",
      image: "/menuitems/Beef-soup.webp",
      categories: [""],
      price: 13.99,
    },
    {
      id: 2,
      name: "BEEF SOUP",
      description: "Central Asian beef soup with vegetables",
      image: "/menuitems/Beef-soup.webp",
      categories: [""],
      price: 13.99,
    },
    {
      id: 3,
      name: "CHUCHVARA",
      description:
        "Ground beef stuffed dumplings served in a soup with vegetables",
      image: "/menuitems/Chuchvara.webp",
      categories: [""],
      price: 13.99,
    },
    {
      id: 4,
      name: "PELMENI",
      description: "Ground beef stuffed dumplings in a flavorful broth",
      image: "/menuitems/Pelmeni.webp",
      categories: [""],
      price: 11.99,
    },
    {
      id: 5,
      name: "MASTAVA",
      description: "Thick, hearty soup of rice, meat, vegetables",
      image: "/menuitems/Mastava.webp",
      categories: [""],
      price: 10.99,
    },
    {
      id: 6,
      name: "LENTIL SOUP",
      description: "Classic lentil soup served with lemon",
      image: "/menuitems/Lentil-soup.webp",
      categories: [""],
      price: 7.99,
    },
  ],
  APPETIZERS: [
    {
      id: 1,
      name: "BOORSOK",
      description: "Fried dough in a shape of puffy pillows",
      image: "/menuitems/Boorsok.webp",
      categories: ["SPECIAL", "H", "V"],
      price: 5.49,
    },
    {
      id: 2,
      name: "CHICKEN SAMSA",
      description: "Central Asian chicken pastry",
      image: "/menuitems/Chicken-samsa.webp",
      categories: ["SPECIAL", "H"],
      price: 5.49,
    },
    {
      id: 3,
      name: "LEPESHKA",
      description: "Central Asian bread",
      image: "",
      categories: ["H", "V"],
      price: 4.99,
    },
    {
      id: 4,
      name: "CHEBUREK with BEEF",
      description: "Savory meat-filled turnover, fried to perfection",
      image: "/menuitems/Cheburek-meat.webp",
      categories: ["H", "V"],
      price: 5.50,
    },
    {
      id: 5,
      name: "CHEBUREK with SPINACH",
      description: "Savory spinach-filled turnover, fried to perfection",
      image: "/menuitems/Cheburek-meat.webp",
      categories: ["H", "V"],
      price: 5.50,
    },
  ],
  SALADS: [
    {
      id: 1,
      name: "CARROT SALAD",
      description: "Crunchy grated carrots dressed with olive oil",
      image: "/menuitems/carrot-salad.webp",
      categories: [""],
      price: 4.99,
    },
    {
      id: 2,
      name: "SHAKARAP",
      description: "Sliced tomatoes with onions seasoned w salt",
      image: "/menuitems/Shakarap.webp",
      categories: [""],
      price: 3.49,
    },
    {
      id: 3,
      name: "GREEK SALAD",
      description: "Crisp Romaine, Creamy Dressing, Parmesan, Garlic Croutons",
      image: "/menuitems/Greek-salad.webp",
      categories: [""],
      price: 10.99,
    },
    {
      id: 4,
      name: "AVOCADO SALAD",
      description: "House-made avocado with vegetables salad",
      image: "/menuitems/Avocado-salad.webp",
      categories: [""],
      price: 9.99,
    },
    {
      id: 5,
      name: "CAESAR SALAD",
      description: "Crisp Romaine, Creamy Dressing, Parmesan, Garlic Croutons",
      image: "/menuitems/Caesar-salad.webp",
      categories: [""],
      price: 10.99,
    },
    {
      id: 6,
      name: "OLIVYE",
      description:
        "Hearty blend: potatoes, sausages, peas, carrots, pickles, eggs, mayo, and more!",
      image: "/menuitems/Olivye.webp",
      categories: [""],
      price: 9.99,
    },
  ],
  "KIDS MENU": [
    {
      id: 1,
      name: "HALAL BURGER",
      description: "House-made cheeseburger",
      image: "",
      categories: [""],
      price: 9,
    },
    {
      id: 2,
      name: "FRENCH FRIES",
      description: "House-made fries served with ketchup",
      image: "",
      categories: [""],
      price: 3.99,
    },
    {
      id: 3,
      name: "CHICKEN NUGGETS",
      description: "Deep-fried boneless chicken pieces",
      image: "",
      categories: [""],
      price: 7.5,
    },
  ],
  "ARZAN GRILL": [
    {
      id: 1,
      name: "BEEF SHAWARMA",
      description: "Beef & lamb wrap with vegies and house-made sauce",
      image: "/menuitems/Beef-shawarma.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 2,
      name: "CHICKEN SHAWARMA",
      description: "Chicken wrap with vegies and house-made sauce",
      image: "/menuitems/Chicken-shawarma.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 3,
      name: "ASSORTI SHAWARMA",
      description: "Beef, lamb & chicken wrap with vegies and house-made sauce",
      image: "/menuitems/Beef-shawarma.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 4,
      name: "VEGGIE SHAWARMA",
      description: "Veggie wrap with french fries and vegetables",
      image: "/menuitems/Veggie-Shawarma.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 5,
      name: "CHEESEBURGER",
      description: "House-made zabiha halal cheeseburger",
      image: "/menuitems/Cheeseburger.webp",
      categories: [""],
      price: 10,
    },
    {
      id: 6,
      name: "DOUBLE CHEESEBURGER",
      description: "House-made zabiha halal double cheeseburger",
      image: "/menuitems/Cheeseburger.webp",
      categories: [""],
      price: 12,
    },
    {
      id: 7,
      name: "GRILLED CHICKEN",
      description: "Grilled chicken served over rice with sauce",
      image: "/menuitems/Grilled-chicken.webp",
      categories: [""],
      price: 12.99,
    },
    {
      id: 8,
      name: "RIBEYE STEAK",
      description:
        "Juicy ribeye, grilled to perfection, served with savory sides",
      image: "/menuitems/Ribeye-steak.webp",
      categories: [""],
      price: 34.99,
    },
    {
      id: 9,
      name: "T-BONE STEAK",
      description: "Juicy, grilled perfection, served with grilled vegetables",
      image: "/menuitems/Ribeye-steak.webp",
      categories: [""],
      price: 34.99,
    },
    {
      id: 12,
      name: "BAKED SALMON",
      description:
        "Juicy baked salmon served with rice and house special sauce",
      image: "/menuitems/Baked-salmon.webp",
      categories: [""],
      price: 20.99,
    },
  ],
  BEVERAGES: [
    {
      id: 1,
      name: "JARMA (1 GAL)",
      description: "",
      image: "",
      categories: [""],
      price: 25,
    },
    {
      id: 1,
      name: "JARMA (1 Lt)",
      description: "",
      image: "",
      categories: [""],
      price: 7.5,
    },
    {
      id: 1,
      name: "POT OF TEA",
      description: "",
      image: "",
      categories: [""],
      price: 2,
    },
    {
      id: 1,
      name: "COMPOTE (1 Lt)",
      description: "",
      image: "",
      categories: [""],
      price: 6.5,
    },
    {
      id: 1,
      name: "NATAKHTARI (1 Lt)",
      description: "",
      image: "",
      categories: [""],
      price: 5,
    },
    {
      id: 1,
      name: "NATAKHTARI (1 glass)",
      description: "",
      image: "",
      categories: [""],
      price: 3,
    },
    {
      id: 1,
      name: "SODA",
      description: "Coke, Pepsi, Fanta, Sprite",
      image: "",
      categories: [""],
      price: 1.5,
    },
    {
      id: 1,
      name: "SODA (glass bottle)",
      description: "",
      image: "",
      categories: [""],
      price: 3,
    },
  ],
  DESSERTS: [
    {
      id: 1,
      name: "HONEY CAKE",
      description:
        "Thin layer cake made with raw honey and a sour cream frosting",
      image: "",
      categories: [""],
      price: 7,
    },
    {
      id: 1,
      name: "MILK CAKE",
      description: "Russian pancake",
      image: "",
      categories: [""],
      price: 7,
    },
    {
      id: 1,
      name: "SOCHINSKIY",
      description: "Sochinskiy",
      image: "",
      categories: [""],
      price: 4,
    },
  ],
  BREAKFAST: [
    {
      id: 1,
      name: "BREAKFAST PLATE",
      description:
        "Central Asian style breakfast with traditional omlette, blinchik (Russian pancake), a cup of kaimak (sour cream), a cup of honey and a pot of tea.",
      image: "",
      categories: [""],
      price: 9.95,
    },
    {
      id: 2,
      name: "BLINI w TVOROG",
      description: "Russian pancake with cottage cheese",
      image: "",
      categories: [""],
      price: 4,
    },
    {
      id: 3,
      name: "BLINI PLAIN",
      description: "Russian pancake",
      image: "",
      categories: [""],
      price: 2,
    },
    {
      id: 4,
      name: "HONEY",
      description: "1 portion of Central Asian honey",
      image: "",
      categories: [""],
      price: 1,
    },
    {
      id: 5,
      name: "JAM",
      description: "1 portion of strawberry or cherries jam",
      image: "",
      categories: [""],
      price: 1,
    },
    {
      id: 6,
      name: "KAIMAK",
      description: "Central Asian sour cream",
      image: "",
      categories: [""],
      price: 3,
    },
    {
      id: 7,
      name: "LEMON",
      description: "1 portion of a lemon",
      image: "",
      categories: [""],
      price: 1.5,
    },
  ],
  KEBABS: [
    {
      id: 1,
      name: "KEBAB SET 1(Chicken&Cheese Lulya)",
      description:
        "1 skewer of chicken kebab and 1 skewer of cheese lulya with french fries & rice",
      image: "/menuitems/Kebab-Set1.webp",
      categories: [""],
      price: 19.99,
    },
    {
      id: 2,
      name: "KEBAB SET 2(Lulya & Lamb)",
      description: "1 skewer of lulya kebab and 1 skewer of lamb kebab w french fries&rice",
      image: "/menuitems/Kebab-Set2.webp",
      categories: [""],
      price: 21.99,
    },
    {
      id: 3,
      name: "KEBAB SET 3(Beef & Cheese Lulya)",
      description: "1 skewer of beef kebab and 1 skewer of cheese lulya with french fries & rice",
      image: "/menuitems/Kebab-Set3.webp",
      categories: [""],
      price: 21.99,
    },
    {
      id: 4,
      name: "KEBAB SET 4(Chicken wings & Beef)",
      description: "1 skewer of chicken wings and 1 skewer of cheese lulya with french fries & rice",
      image: "/menuitems/Kebab-Set4.webp",
      categories: [""],
      price: 21.99,
    },
    {
      id: 5,
      name: "LAMB CHOPS",
      description: "1 skewer of grilled lamb chops served with potatoes and vegies",
      image: "/menuitems/Lamb-chops.webp",
      categories: [""],
      price: 26.99,
    },
    {
      id: 6,
      name: "LULYA KEBAB",
      description: "1 skewer of grilled minced beef with french fries and rice",
      image: "/menuitems/Lulya-kebab.webp",
      categories: [""],
      price: 8.99,
    },
    {
      id: 7,
      name: "BEEF KEBAB",
      description: "1 skewer of grilled beef cubes with french fries and rice",
      image: "/menuitems/Beef-shashlyk.webp",
      categories: [""],
      price: 11.99,
    },
    {
      id: 8,
      name: "LAMB KEBAB",
      description: "1 skewer of grilled lamb cubes with french fries and rice",
      image: "/menuitems/Beef-shashlyk.webp",
      categories: [""],
      price: 12.99,
    },
    {
      id: 9,
      name: "CHICKEN KEBAB",
      description: "1 skewer of grilled chicken cubes with french fries and rice",
      image: "/menuitems/Chicken-shashlyk.webp",
      categories: [""],
      price: 8.99,
    },
    {
      id: 10,
      name: "CHICKEN WINGS",
      description: "1 skewer of grilled chicken wings with french fries and rice",
      image: "/menuitems/Chicken-shashlyk.webp",
      categories: [""],
      price: 8.99,
    },
    {
      id: 11,
      name: "KEBAB LOVERS",
      description: "Variety of 6 skewered kebabs and 1 skewer of lamb chops served with rice and french fries",
      image: "/menuitems/mixed-kebab.webp",
      categories: [""],
      price: 8.99,
    },
  ],
  "SPECIALORDER": [
    {
      id: 1,
      name: "Tashkent plov",
      description: "",
      image: "",
      categories: [""],
      price: 140,
    },
    {
      id: 2,
      name: "Uzgen rice plov",
      description: "",
      image: "",
      categories: [""],
      price: 150,
    },
    {
      id: 3,
      name: "Lazer rice plov",
      description: "",
      image: "",
      categories: [""],
      price: 120,
    },
    {
      id: 4,
      name: "Beshbarmak",
      description: "",
      image: "/menuitems/Beshbarmak.webp",
      categories: [""],
      price: 70,
    },
    {
      id: 5,
      name: "Boorsok",
      description: "",
      image: "/menuitems/Boorsok.webp",
      categories: [""],
      price: 20,
    },
    {
      id: 6,
      name: "Kuurdak (2 kg min)",
      description: "",
      image: "",
      categories: [""],
      price: 65,
    },
  ],
};
